/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */







declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  Mutation: {};
  Post: { // root type
    body?: string | null; // String
    id?: number | null; // Int
    published?: boolean | null; // Boolean
    title?: string | null; // String
  }
  Query: {};
  Subject: { // root type
    deleted?: boolean | null; // Boolean
    id?: number | null; // Int
    itemOrder?: number | null; // Int
    level?: number | null; // Int
    levelName?: string | null; // String
    name?: string | null; // String
  }
  User: { // root type
    createTime: number; // Int!
    deleted: boolean; // Boolean!
    id: number; // Int!
    mobile: string; // String!
    name: string; // String!
    sex: number; // Int!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  Mutation: { // field return type
    createDraft: NexusGenRootTypes['Post'] | null; // Post
    createSubject: NexusGenRootTypes['Subject'] | null; // Subject
    createUser: NexusGenRootTypes['User'] | null; // User
    deleteUser: NexusGenRootTypes['User'] | null; // User
    publish: NexusGenRootTypes['Post'] | null; // Post
    updateUser: NexusGenRootTypes['User'] | null; // User
  }
  Post: { // field return type
    body: string | null; // String
    id: number | null; // Int
    published: boolean | null; // Boolean
    title: string | null; // String
  }
  Query: { // field return type
    Subject: Array<NexusGenRootTypes['Subject'] | null> | null; // [Subject]
    User: Array<NexusGenRootTypes['User'] | null> | null; // [User]
    drafts: Array<NexusGenRootTypes['Post'] | null> | null; // [Post]
    posts: Array<NexusGenRootTypes['Post'] | null> | null; // [Post]
  }
  Subject: { // field return type
    deleted: boolean | null; // Boolean
    id: number | null; // Int
    itemOrder: number | null; // Int
    level: number | null; // Int
    levelName: string | null; // String
    name: string | null; // String
  }
  User: { // field return type
    createTime: number; // Int!
    deleted: boolean; // Boolean!
    id: number; // Int!
    mobile: string; // String!
    name: string; // String!
    sex: number; // Int!
  }
}

export interface NexusGenFieldTypeNames {
  Mutation: { // field return type name
    createDraft: 'Post'
    createSubject: 'Subject'
    createUser: 'User'
    deleteUser: 'User'
    publish: 'Post'
    updateUser: 'User'
  }
  Post: { // field return type name
    body: 'String'
    id: 'Int'
    published: 'Boolean'
    title: 'String'
  }
  Query: { // field return type name
    Subject: 'Subject'
    User: 'User'
    drafts: 'Post'
    posts: 'Post'
  }
  Subject: { // field return type name
    deleted: 'Boolean'
    id: 'Int'
    itemOrder: 'Int'
    level: 'Int'
    levelName: 'String'
    name: 'String'
  }
  User: { // field return type name
    createTime: 'Int'
    deleted: 'Boolean'
    id: 'Int'
    mobile: 'String'
    name: 'String'
    sex: 'Int'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createDraft: { // args
      body: string; // String!
      title: string; // String!
    }
    createSubject: { // args
      itemOrder: number; // Int!
      level: number; // Int!
      levelName: string; // String!
      name: string; // String!
    }
    createUser: { // args
      mobile?: string | null; // String
      name?: string | null; // String
      sex?: number | null; // Int
    }
    deleteUser: { // args
      id: number; // Int!
    }
    publish: { // args
      draftId: number; // Int!
    }
    updateUser: { // args
      id: number; // Int!
      mobile?: string | null; // String
      name?: string | null; // String
      sex?: number | null; // Int
    }
  }
  Query: {
    User: { // args
      criteriaStr?: string | null; // String
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: any;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}